menu:
  Home: /
  Archives: /archives
  About: /about
  RSS: /atom.xml

# duoshuo comment
duoshuo: false
duoshuo_name: DaraW

# disqus comment
disqus: true
disqus_shortname: daraw

# google analytics
googleTrackId: UA-75095706-1